users
-user_id
-user_surname
-user_lastname
-user_course
-user_registration
-user_nickname
-user_salt
-user_password
-created_at
-upfated_at

courses
-course_id
-course_code
-course_name
-created_at
-updated_at

